### ISSUE TITLE
Database/users-table

### ISSUE THREAD

**Issue by carlosra0345** [aggie-coding-club/SecuroChat#40]
# Create users table containing the following attributes
- user_id
- username
- phone
- email
- online_status
- last_online

**Comment by oliverkstalker** [comment]
Implemented users table in database.sql with following format:

CREATE TABLE users (
    user_id UUID PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    phone TEXT,
    email VARCHAR(100) UNIQUE NOT NULL,
    online_status BOOLEAN DEFAULT FALSE,
    last_online TIMESTAMP
);
