### ISSUE TITLE
Database/friends

### ISSUE THREAD

**Issue by carlosra0345** [aggie-coding-club/SecuroChat#43]
# Create friends table with attributes
- friendship_id
- user_id
- friend_id
- status

**Comment by oliverkstalker** [comment]
Implemented friends table with following format in database.sql:

CREATE TABLE friends (
    friendship_id INT PRIMARY KEY,
    user_id INT REFERENCES users(user_id),
    friend_id INT REFERENCES users(user_id),
    status VARCHAR(16) NOT NULL
);
