### ISSUE TITLE
Database/conversations-table

### ISSUE THREAD

**Issue by carlosra0345** [aggie-coding-club/SecuroChat#47]
# Create conversations table with attributes
- conversation_id
- conversation_type
- conversation_title
- created_at
- updated_at
- creator_id

**Comment by oliverkstalker** [comment]
Implemented conversations table in database.sql with following format:
CREATE TABLE conversations (
    conversation_id INT PRIMARY KEY,
    conversation_type VARCHAR(16) NOT NULL,
    conversation_title VARCHAR(32),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    creator_id INT REFERENCES users(user_id)
);
