### ISSUE TITLE
Database/participants-table

### ISSUE THREAD

**Issue by carlosra0345** [aggie-coding-club/SecuroChat#48]
# Create participants table with attributes
- participant_id
- user_id
- conversation_id

**Comment by oliverkstalker** [comment]
Created participants table in database.sql with following format:

CREATE TABLE participants (
    participant_id INT PRIMARY KEY,
    user_id INT REFERENCES users(user_id),
    conversation_id INT REFERENCES conversations(conversation_id)
);
